# Generated by Django 4.2.1 on 2023-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ('name',),
            },
        ),
    ]
